export enum DeviceEventType {
  LockedViaBluetooth = 32,
  LockedViaButton = 34,
  LockedAuto = 36,
  LockedManual = 38,
  UnlockedViaBluetooth = 33,
  UnlockedViaButton = 35,
  UnlockedAuto = 37,
  UnlockedManual = 39,
  PartiallyOpenViaBluetooth = 54,
  PartiallyOpenViaButton = 48,
  PartiallyOpenAuto = 49,
  PartiallyOpenManual = 47,
  SpringPulledViaBluetooth = 51,
  SpringPulledViaButton = 52,
  SpringPulledAuto = 55,
  SpringPulledManual = 53,
  Jammed = 40,
  PowerOff = 41,
  PowerOn = 42,
  Calibration = 43,
  BatteryCharging = 46,
  BatteryStoppedCharging = 50,
  FirmwareUpdatedByBridge = 224,
  FirmwareUpdatedByMobile = 225
}
